### ISSUE TITLE
Filename should contain 'heapprofile' instead of 'heapsnapshot'

### ISSUE THREAD

**Issue by deep9** [wallet77/v8-inspector-api#1]
https://github.com/wallet77/v8-inspector-api/blob/dd4564e512384b103dd31434a2f2996ce68230db/src/heap.js#L25

When the suffix is heapsnapshot, dev tools won't load the file. With heapprofile it works fine. Took me some time to figure this out ;)

**Comment by wallet77** [comment]
I will fix this ASPAP ;)

**Comment by wallet77** [comment]
@deep9 should be fixed in 1.0.2
