### ISSUE TITLE
getting `segmentation fault  node` while trying `inspector.heap.takeSnapshot()` with `node v14.17.6`

### ISSUE THREAD

**Issue by vimalnegi** [wallet77/v8-inspector-api#15]

**Comment by wallet77** [comment]
@vimalnegi did you try without the S3 exporter ?

As mentionned in the readme there is an issue with the new AWS sdk and the method takeSnapshot(). But memory sampling is ok.

If you don't need it, replace:
`storage: {
        type: 's3',
`
with
`storage: {
        type: 'raw',`
