### ISSUE TITLE
Usage with server backend app for on-demand profiling

### ISSUE THREAD

**Issue by sokyrynskyi** [wallet77/v8-inspector-api#19]
I want to use the lib for on-demand (i.e. triggered by custom HTTP endpoints) CPU profiling with a typical backend app (express, Kafka, etc.).

As I see in [the example ](https://github.com/wallet77/v8-inspector-api?tab=readme-ov-file#cpu-profiling) the single `Inspector` instance is supposed to be used. However it does create and connect a `Session` in the constructor:
https://github.com/wallet77/v8-inspector-api/blob/3736a6f3ebd1d1899e1c64b5b99bbc82833537b6/index.js#L18-L19

So if I create the singleton `Inspector` instance once (on the app start-up) -- is there any overhead related with the constructor code? (most of the time profiling is not supposed to be used, so it's required not to impact the app's performance/resources until it's actually triggered)
Or should I instead create new `Inspector` instance each time profiling is triggered? If yes -- how to make sure the object is GC-ed?
Same question but in other words -- how is `Inspector` instance supposed to be used for a long-running app, as a (global) singletone or as a local reference?

**Comment by wallet77** [comment]
Hi @sokyrynskyi ,

Until you use the inspector there is no overhead with it (except the minimum memory for the inspector constructor).

I think in your case the best is to create and instantiate the inspector only once, then you just have to trigger the profiling on-demand with the method `await inspector.profiler.start()`.

If you really need to close the inspector then you just have to call `inspector.destroy()`. I'm sorry it's not well documented.

**Comment by wallet77** [comment]
For the last question, I think the best should be to use a global singletone as it's not related to your code and it can be called from everywhere.
