### ISSUE TITLE
Dependencies are quite large

### ISSUE THREAD

**Issue by jdmarshall** [wallet77/v8-inspector-api#9]
Scanning my project looking for node_modules creep, I discovered that this module has two dependencies that are 120MB between the two of them.  This is... substantial.

du -sh * | sort -h
 16K	ieee754
 24K	async-await-retry
 24K	base64-js
 32K	isarray
 32K	punycode
 36K	inspector-api
 64K	xml2js
 72K	querystring
 76K	sax
 92K	url
100K	uuid
104K	events
168K	xmlbuilder
320K	jmespath
372K	buffer
 59M	@voodoo.io
 62M	aws-sdk

aws-sdk has a lot of what look like source versus output problems that probably could use an .npmignore fix.
But @voodoo.io's main dependency is also aws-sdk, which seems to be on a different  version number?

**Comment by wallet77** [comment]
Hi @jdmarshall,

I will see how to improve that.
@voodoo.io can be removed quite easily.
For aws SDK I know their v3 is lighter, but it will probably lead to a major version to drop the support of older node's version.

Anyway good catch!

**Comment by wallet77** [comment]
I will use only this now: https://www.npmjs.com/package/@aws-sdk/client-s3

**Comment by jdmarshall** [comment]
I suspect letting voodoo pick the number reduces things quite a bit, but the direct client is definitely smaller.

**Comment by wallet77** [comment]
@jdmarshall Shipped in version 1.4.0

**Comment by jdmarshall** [comment]
That definitely helps, thanks. I think it's still about 25MB but that's much better.
